### ISSUE TITLE
Unresponsive projects section for mobile screens

### ISSUE THREAD

**Issue by PakmanGames** [At104/at104.github.io#1]
# Hey I've written some CSS that might be of use to your portfolio as it's not very responsive on mobile devices

The styling applies on devices with a width of 768px or smaller (common for foldable phones and tablets)

```css
/* Most foldable phones / tablets start at 768px */
@media (max-width: 768px) {
  .projects-container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .project img {
    /* you can figure out the right sizes */
    width: 200px;
    height: auto;
  }
}
```
After applying my changes it should look like this:
![localhost_5500_(iPhone 12 Pro)](https://github.com/user-attachments/assets/4bfbf9fc-5e97-483b-b87c-14d4fc8470f7)
